"""add portfolio targets

Revision ID: 3db4db18a970
Revises: 7cbf9c8584e8
Create Date: 2026-09-06 15:50:12.446797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db4db18a970'
down_revision: Union[str, Sequence[str], None] = '7cbf9c8584e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=50), nullable=False),
    sa.Column('target_key', sa.String(length=100), nullable=False),
    sa.Column('target_percentage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dimension', 'target_key', name='uq_portfolio_target_dimension_key')
    )
    op.create_index(op.f('ix_portfolio_targets_dimension'), 'portfolio_targets', ['dimension'], unique=False)
    op.create_index(op.f('ix_portfolio_targets_id'), 'portfolio_targets', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_targets_target_key'), 'portfolio_targets', ['target_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_targets_target_key'), table_name='portfolio_targets')
    op.drop_index(op.f('ix_portfolio_targets_id'), table_name='portfolio_targets')
    op.drop_index(op.f('ix_portfolio_targets_dimension'), table_name='portfolio_targets')
    op.drop_table('portfolio_targets')
    # ### end Alembic commands ###
