"""add_broker_transaction_id

Revision ID: 63bf2eb7c64b
Revises: b68b844582b7
Create Date: 2026-08-09 15:26:17.329781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63bf2eb7c64b'
down_revision: Union[str, Sequence[str], None] = 'b68b844582b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('broker_transaction_id', sa.String(length=100), nullable=True))
    op.alter_column('transactions', 'transaction_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_index(op.f('ix_transactions_broker_transaction_id'), 'transactions', ['broker_transaction_id'], unique=True)
    op.create_index(op.f('ix_transactions_investment_id'), 'transactions', ['investment_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_investment_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_broker_transaction_id'), table_name='transactions')
    op.alter_column('transactions', 'transaction_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('transactions', 'broker_transaction_id')
    # ### end Alembic commands ###
