"""add price history

Revision ID: 7cbf9c8584e8
Revises: 8f366e774a6e
Create Date: 2026-09-02 15:17:05.745555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbf9c8584e8'
down_revision: Union[str, Sequence[str], None] = '8f366e774a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('market_ticker', sa.String(length=30), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investment_id', 'price_date', name='uq_price_history_investment_date')
    )
    op.create_index(op.f('ix_price_history_id'), 'price_history', ['id'], unique=False)
    op.create_index(op.f('ix_price_history_investment_id'), 'price_history', ['investment_id'], unique=False)
    op.create_index(op.f('ix_price_history_market_ticker'), 'price_history', ['market_ticker'], unique=False)
    op.create_index(op.f('ix_price_history_price_date'), 'price_history', ['price_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_price_date'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_market_ticker'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_investment_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_id'), table_name='price_history')
    op.drop_table('price_history')
    # ### end Alembic commands ###
