"""add fx rate to cash movements

Revision ID: 8f366e774a6e
Revises: 26e822426eeb
Create Date: 2026-09-02 13:07:05.979642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f366e774a6e'
down_revision: Union[str, Sequence[str], None] = '26e822426eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_movements', sa.Column('fx_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cash_movements', 'fx_rate')
    # ### end Alembic commands ###
