"""add real estate loan end date

Revision ID: a03bd00c6f35
Revises: 89a4f9409855
Create Date: 2026-09-10 17:30:13.609965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a03bd00c6f35'
down_revision: Union[str, Sequence[str], None] = '89a4f9409855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_estate_properties', sa.Column('loan_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('real_estate_properties', 'loan_end_date')
    # ### end Alembic commands ###
