"""add_cash_movements

Revision ID: b9e119386913
Revises: 63bf2eb7c64b
Create Date: 2026-08-09 16:00:47.072415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e119386913'
down_revision: Union[str, Sequence[str], None] = '63bf2eb7c64b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker', sa.String(length=100), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('broker_movement_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_movements_broker'), 'cash_movements', ['broker'], unique=False)
    op.create_index(op.f('ix_cash_movements_broker_movement_id'), 'cash_movements', ['broker_movement_id'], unique=True)
    op.create_index(op.f('ix_cash_movements_id'), 'cash_movements', ['id'], unique=False)
    op.create_index(op.f('ix_cash_movements_movement_date'), 'cash_movements', ['movement_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_movements_movement_date'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_broker_movement_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_broker'), table_name='cash_movements')
    op.drop_table('cash_movements')
    # ### end Alembic commands ###
