"""add_transaction_lots

Revision ID: c7a5340c009a
Revises: 6e1796bc33ee
Create Date: 2026-08-06 02:19:38.795021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a5340c009a'
down_revision: Union[str, Sequence[str], None] = '6e1796bc33ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('buy_transaction_id', sa.Integer(), nullable=False),
    sa.Column('original_quantity', sa.Float(), nullable=False),
    sa.Column('remaining_quantity', sa.Float(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['buy_transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_lots_buy_transaction_id'), 'transaction_lots', ['buy_transaction_id'], unique=True)
    op.create_index(op.f('ix_transaction_lots_id'), 'transaction_lots', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_lots_investment_id'), 'transaction_lots', ['investment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_lots_investment_id'), table_name='transaction_lots')
    op.drop_index(op.f('ix_transaction_lots_id'), table_name='transaction_lots')
    op.drop_index(op.f('ix_transaction_lots_buy_transaction_id'), table_name='transaction_lots')
    op.drop_table('transaction_lots')
    # ### end Alembic commands ###
