"""add_broker_dividend_id

Revision ID: e86232aafddd
Revises: b9e119386913
Create Date: 2026-08-09 17:14:44.926266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86232aafddd'
down_revision: Union[str, Sequence[str], None] = 'b9e119386913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dividends', sa.Column('broker_dividend_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_dividends_broker_dividend_id'), 'dividends', ['broker_dividend_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dividends_broker_dividend_id'), table_name='dividends')
    op.drop_column('dividends', 'broker_dividend_id')
    # ### end Alembic commands ###
